
export enum Permissions {
    CREATE_USER = 'CREATE_USER',
    READ_USER = 'READ_USER',
    DELETE_USER = 'DELETE_USER',
    UPDATE_USER = 'UPDATE_USER',
    MANAGE_ROLE = 'MANAGE_ROLE',
    ASSIGN_ROLE = 'ASSIGN_ROLE',
}
